name: Build and deploy .NET Core application to Web App UserServicePresentation20250718014607 with API Management Service UserServicePresentationapi-UserServicePresentation

on:
  push:
    branches:
      - ZhengTao/Backend

env:
  AZURE_WEBAPP_NAME: UserServicePresentation20250718014607
  AZURE_WEBAPP_PACKAGE_PATH: ./deploy-package
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: testresource
  AZURE_APIM_SERVICENAME: UserServicePresentationapi
  AZURE_APIM_API_ID: UserServicePresentation
  AZURE_APIM_APPSERVICEURL: https://userservicepresentation20250718014607-bteyguc4b5djgdav.canadacentral-01.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
  SWASHBUCKLE_DOTNET_CORE_VERSION: 7.0.x
  API_IMPORT_SPECIFICATION_PATH: ./deploy-package/swagger.json
  API_IMPORT_DLL: ./deploy-package/UserService.Presentation.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: UserService/UserService.Presentation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Setup .NET 7 runtime (for swagger CLI tool)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build

      - name: Create clean deployment directory
        run: |
          mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          echo "Created deployment directory"

      - name: Publish application
        run: |
          dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          echo "Published to deployment package"
        env:
          ASPNETCORE_ENVIRONMENT: Production

      - name: Install Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

      - name: Generate OpenAPI Specification Document
        run: |
          swagger tofile \
            --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" \
            "${{ env.API_IMPORT_DLL }}" \
            "${{ env.API_IMPORT_VERSION }}"
        env:
          ASPNETCORE_ENVIRONMENT: swagger

      - name: Verify deployment package
        run: |
          echo "Deployment package contents:"
          ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: webapp

      - name: Verify deployment package
        run: |
          echo "Deployment package contents:"
          ls -la webapp/
          echo "Checking for essential files:"
          ls -la webapp/*.dll | head -5 || echo "No DLL files found"
          ls -la webapp/*.json || echo "No JSON files found"
          
          # Check if we have the main application DLL
          if [ -f "webapp/UserService.Presentation.dll" ]; then
            echo "✓ Main application DLL found"
          else
            echo "✗ Main application DLL not found"
            echo "Available DLLs:"
            find webapp -name "*.dll" | head -10
          fi
          
          # Check for web.config
          if [ -f "webapp/web.config" ]; then
            echo "✓ web.config found"
          else
            echo "✗ web.config not found"
          fi

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.UserServicePresentationapi_SPN }}

      - name: Set Azure App Service Environment
        run: |
          az webapp config appsettings set \
            --name "${{ env.AZURE_WEBAPP_NAME }}" \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --settings "ASPNETCORE_ENVIRONMENT=Production"

      - name: Deploy to Azure Web App
        run: |
          cd webapp
          # Check if we have the main executable
          ls -la UserService.Presentation* || echo "Main executable not found"
          
          # Create a clean zip without problematic files
          zip -r ../webapp.zip . \
            -x "*.pdb" \
            -x "runtimes/browser/*" \
            -x "appsettings.Development.json"
          
          cd ..
          
          # Check zip size
          ls -lh webapp.zip
          
          # Deploy with better error handling
          az webapp deploy \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --name "${{ env.AZURE_WEBAPP_NAME }}" \
            --src-path webapp.zip \
            --type zip \
            --async false \
            --timeout 600
            
      - name: Get deployment logs on failure
        if: failure()
        run: |
          echo "Getting deployment logs..."
          az webapp log deployment show \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --name "${{ env.AZURE_WEBAPP_NAME }}" || echo "Could not retrieve logs"
          
          echo "Getting latest deployment status..."
          curl -s "https://${{ env.AZURE_WEBAPP_NAME }}.scm.canadacentral-01.azurewebsites.net/api/deployments/latest" || echo "Could not get deployment status"

      - name: Wait for deployment to complete
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30

      - name: Deploy to Azure Web App (Alternative method)
        if: failure()
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: webapp

      - name: Import API into Azure API Management
        run: |
          az apim api import \
            --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --service-name "${{ env.AZURE_APIM_SERVICENAME }}" \
            --api-id "${{ env.AZURE_APIM_API_ID }}" \
            --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" \
            --specification-path "swagger.json" \
            --specification-format OpenApi \
            --subscription-required false

      - name: Logout from Azure
        run: az logout