# .github/workflows/deploy.yml

name: Build and deploy ASP.NET Core app to Azure Web App - UserServicePresentation20250718014607

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'
  PUBLISH_DIR: './publish'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore UserService/UserService.Presentation

      - name: Build the project
        run: dotnet build UserService/UserService.Presentation --configuration Release --no-restore

      - name: Publish the app
        run: dotnet publish UserService/UserService.Presentation -c Release -o ${{ env.PUBLISH_DIR }} --no-build

      - name: Upload publish directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published app artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./deploy-dir

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_975407E9AF1649A7ABE0083ED3C94B2A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5566DCE38BF048FA945A1FAC01E910A1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BF119FB0DB40464BA7E0ADDD644FD13B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'UserServicePresentation20250718014607'
          slot-name: 'Production'
          package: ./deploy-dir
