name: Build and Deploy .NET API to Azure with APIM

on:
  push:
    branches:
      - ZhengTao/Backend

env:
  AZURE_WEBAPP_NAME: UserServicePresentation20250718014607
  AZURE_WEBAPP_PACKAGE_PATH: publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: testresource
  AZURE_APIM_SERVICENAME: UserServicePresentationapi
  AZURE_APIM_API_ID: UserServicePresentation
  AZURE_APIM_APPSERVICEURL: https://userservicepresentation20250718014607-bteyguc4b5djgdav.canadacentral-01.azurewebsites.net
  SWASHBUCKLE_CLI_VERSION: 6.5.0
  API_PROJECT_FOLDER: UserService/UserService.Presentation
  API_DLL_PATH: UserService/UserService.Presentation/bin/Release/net8.0/UserService.Presentation.dll
  API_IMPORT_VERSION: v1
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.API_PROJECT_FOLDER }}

      - name: Build
        run: dotnet build ${{ env.API_PROJECT_FOLDER }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.API_PROJECT_FOLDER }} --no-build

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_FOLDER }} --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCKLE_CLI_VERSION }}

      - name: Generate Swagger
        run: |
          mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          swagger tofile --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/swagger.json "${{ env.API_DLL_PATH }}" "${{ env.API_IMPORT_VERSION }}"
        env:
          ASPNETCORE_ENVIRONMENT: swagger

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: webapp

      - name: Zip content
        run: |
          cd webapp
          zip -r ../webapp.zip .
        shell: bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.UserServicePresentationapi_SPN }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: webapp.zip

      - name: Import API into Azure API Management
        run: |
          az apim api import \
            --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --service-name "${{ env.AZURE_APIM_SERVICENAME }}" \
            --api-id "${{ env.AZURE_APIM_API_ID }}" \
            --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" \
            --specification-path "webapp/swagger.json" \
            --specification-format OpenApi \
            --subscription-required false

      - name: Logout Azure
        run: az logout
