name: Build and deploy .NET Core app to Web App & API Management

on:
  push:
    branches:
      - ZhengTao/Backend

env:
  AZURE_WEBAPP_NAME: UserServicePresentation20250718014607
  AZURE_WEBAPP_PACKAGE_PATH: UserService/UserService.Presentation/publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: testresource
  AZURE_APIM_SERVICENAME: UserServicePresentationapi
  AZURE_APIM_API_ID: UserServicePresentation
  AZURE_APIM_APPSERVICEURL: https://userservicepresentation20250718014607-bteyguc4b5djgdav.canadacentral-01.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
  SWASHBUCKLE_DOTNET_CORE_VERSION: 7.0.x
  API_IMPORT_SPECIFICATION_PATH: swagger.json
  API_IMPORT_DLL: UserService/UserService.Presentation/bin/Release/net8.0/UserService.Presentation.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: UserService/UserService.Presentation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build

      - name: Publish
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

      - name: Generate Swagger
        run: >
          swagger tofile
          --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}"
          "${{ env.API_IMPORT_DLL }}"
          "${{ env.API_IMPORT_VERSION }}"
        env:
          ASPNETCORE_ENVIRONMENT: swagger

      - name: Create deployment zip
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          zip -r ../../../../webapp.zip ./*

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: webapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.UserServicePresentationapi_SPN }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: webapp.zip
          clean: true

      - name: Import API into Azure API Management
        run: |
          az apim api import \
            --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" \
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" \
            --service-name "${{ env.AZURE_APIM_SERVICENAME }}" \
            --api-id "${{ env.AZURE_APIM_API_ID }}" \
            --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" \
            --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" \
            --specification-format OpenApi \
            --subscription-required false

      - name: Logout of Azure
        run: az logout
